name: Release
on:
  push:
    branches:
      - master
      - next
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Change directory to `@vime/core`
        run: cd packages/core
      - name: Install dependencies
        uses: cypress-io/github-action@v2
        with:
          runTests: false
      - name: Run unit tests
        run: npm run test:unit.coverage
      - name: Prepare for e2e tests
        run: npm run coverage:e2e.prepare
      - name: Run e2e tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: npm run serve:public
          wait-on: 'http://localhost:3334'
          browser: chrome
          headless: true
          record: true
          parallel: true
          group: 'GitHub Actions'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      - name: Build coverage report
        run: npm run coverage:combine && npx codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  release:
    name: Release
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install pnpm
        run: curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node
      - name: Install dependencies
        run: pnpm install --filter ./packages
      - name: Build packages
        run: pnpm run build --filter vime
      - name: Release packages
        run: pnpm run release --filter vime
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}