name: Release

on:
  push:
    branches:
      - release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna to correctly version)
          fetch-depth: '0'

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 16

      - name: Cache Dependencies
        id: deps
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
            ./packages/angular/node_modules
            ./packages/core/node_modules
            ./packages/react/node_modules
            ./packages/svelte/node_modules
            ./packages/vue/node_modules
            ./packages/vue-next/node_modules
          key: ${{ runner.os }}-${{ hashFiles('packages/*/package-lock.json') }}

      - name: Install Dependencies
        if: steps.rootDeps.outputs.cache-hit != 'true'
        run: |
          npm ci
          npm run bootstrap

      - name: Build
        run: npm run build

      - name: Setup Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        run: npm run release:ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push Commits
        run: git push origin main
